apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:masters
      rolearn: arn:aws:iam::942024905707:role/UdacityFlaskDeployCBKubectlRole
      username: build
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::942024905707:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-UCR3YZAFXZDW
      username: system:node:{{EC2PrivateDNSName}}
kind: ConfigMap
metadata:
  creationTimestamp: "2023-05-15T13:41:58Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "3166"
  uid: 11afbfea-6d86-4fae-a909-6dd88ac54bcd
